### ISSUE TITLE
Predlog

### ISSUE THREAD

**Issue by Trzinka** [frlequ/home-assistant-network-tariff#19]
S pomočjo Žiga Carl, ki je delno predelal tvoj add on sem ga uspel še malo bolj dodelati, da dobim:
![Tarifi+Bloki](https://github.com/user-attachments/assets/4835e0c3-7a2f-4e4f-9a92-8d5ff14edb09)

Za tarifi sem naredil sensor:
```yaml
#============================================
# Tarifi
#============================================
  - platform: template
    sensors:
      tarifi:
        friendly_name: "Tarifi"
        value_template: >
          {% set current_month = now().month %}
          {% if current_month >= 11 or current_month <= 2 %}
            Visoka tarifa
          {% else %}
            Nizka tarifa
          {% endif %}
        unique_id: c9214188-d611-400c-99df-3b1ce45622ae
```
da dobim:
![Tarifi](https://github.com/user-attachments/assets/33187496-b261-4cf9-acd1-52c5bdd9b7fe)

z tvojim add onom se trenutno da prikazati:
![Elektro network tariff](https://github.com/user-attachments/assets/24e0aa0a-ba27-43ea-8137-013bf1173285)
kar je odlično, ker si dodal še nekaj predlogov.

S prej omenjeno predelavo pa se da dobiti še:
![Bloki](https://github.com/user-attachments/assets/e15fa33f-da46-4148-a1d5-3fcb63b84c80)

Kar nekaj vprašanj sem imel na FB kako sem dobil te podatke in me zanima, če bi jih ti dodal, da nebi bilo toliko add-onov. Načeloma niti nimam predznanja, da bi nudil pomoč. Kolikor vidim ti obvladaš zadevo.

Tukaj je "moja" koda, če želiš dodati še manjkajoče funcije oziroma preimenovati sedanje zaradi lepšega prikaza:
[elektro_bloki.zip](https://github.com/user-attachments/files/18229269/elektro_bloki.zip)

**Še enkrat HVALA za tvoj odločno delo in nesebičen trud.**
