### ISSUE TITLE
Component do not allow set entity_id

### ISSUE THREAD

**Issue by DejanBukovec** [frlequ/home-assistant-network-tariff#8]
Component do not allow set name and entity_id in configuration so there is no way to rename entity and set different options...

![slika](https://github.com/user-attachments/assets/ad12adc3-e316-47f7-b4a7-21ee209855d1)

**Comment by frlequ** [comment]
Added feature in the latest version: https://github.com/frlequ/home-assistant-network-tariff/pull/12

You can now use:
```yaml
sensor:
  - platform: elektro_network_tariff
    name: "Custom Tariff Sensor"
    entity_id: "sensor.custom_tariff_sensor"
```
